import { ReactNode } from "react";

/** Same path as PNG hero with `.webp` extension (generated by `npm run build:hero-webp`). */
function heroWebpSrc(pngPath: string): string {
  return pngPath.replace(/\.png$/i, ".webp");
}

export interface HeroProps {
  title: string;
  subtitle?: string;
  mobile: string;
  tablet: string;
  desktop: string;
  focalPoint?: string;
  alt?: string;
  standalone?: boolean;
  children?: ReactNode;
}

export default function Hero({
  title,
  subtitle,
  mobile,
  tablet,
  desktop,
  focalPoint = "center",
  alt = "",
  standalone = false,
  children,
}: HeroProps) {
  const position =
    focalPoint === "top" ? "center top" : focalPoint === "bottom" ? "center bottom" : "center center";

  return (
    <section
      className={`page-hero ${standalone ? "page-hero--standalone" : ""}`}
      aria-labelledby="page-hero-title"
    >
      <div className="page-hero__image-wrap">
        <picture>
          <source type="image/webp" media="(min-width: 1024px)" srcSet={heroWebpSrc(desktop)} />
          <source media="(min-width: 1024px)" srcSet={desktop} />
          <source type="image/webp" media="(min-width: 768px)" srcSet={heroWebpSrc(tablet)} />
          <source media="(min-width: 768px)" srcSet={tablet} />
          <source type="image/webp" media="(max-width: 767px)" srcSet={heroWebpSrc(mobile)} />
          <img
            src={mobile}
            alt={alt}
            className="page-hero__img"
            loading="eager"
            fetchPriority="high"
            style={{ objectPosition: position }}
          />
        </picture>
      </div>
      <div className="page-hero__content">
        <h1 id="page-hero-title" className="page-hero__title">
          {title}
        </h1>
        {subtitle && <p className="page-hero__subtitle">{subtitle}</p>}
        {children}
      </div>
    </section>
  );
}
